### PR TITLE
Javascript calling luascript fairly transparantly.

### PR DESCRIPTION
**Pull request by o-jasper**
Still missing lua rock and tests.(i have been working very.. test-less lately)

There is [a readme in there](https://github.com/o-jasper/pegasus.lua/blob/PegasusJs/src/PegasusJs/readme.md).

### CODE REVIEW

**Comment by EvandroLG** [comment]
It's great!
But I think that it's a new project, because my idea with Pegasus is design something extremely simple to use, with few features. The other idea is create a mechanism to insert plugins to extend the Pegasus' functionality.

I would like to see PegasusJS as a new project :)

What do you think?

**Comment by o-jasper** [comment]
I am perfectly fine with separating it off into a separate little library. Its your project :)

The approach i made here basically requires the user to insert the script, and make sure the handler is called at the appropriate place. I suppose this could be asking for disorganized code if extended too far.

So that is basically what the plugins are for? To plugin-ize, this thing, i basically make `:pluginsNewRequestResponse` return true for a js-function-to-lua -appropriate path, or when getting the `:script()`. Instead of "inserting at a appropriate place"(which was silly of me, actually..) users have to `<script src="plugin/PegasusJs/index.js"></script>` in the appropriate place. (or whatever path makes most sense/is overridden by user) Plugin creation-time the functions would get defined. I guess that would be quite a bit neater.

I suppose the older version could similarly get rid of `:script()`, just by getting rid of `:script`, and stuffing it all into `:respond()`.

**Comment by o-jasper** [comment]
(note: dont mean anything with that commit)

**Comment by o-jasper** [comment]
Shall i just separate-repo this, calling it PegasusJs okey?(suggestions?)

Don't see modules as really at a point where i should implement them?

**Comment by EvandroLG** [comment]
Hi Jasper,

I think it will works better like a new library, man!
My opinion is that pegasus.lua needs to be a very small http server. Using it developers should be able to create new components.

When PegasusJS is ready, let me know. I would like to share it ;)

**Comment by o-jasper** [comment]
I put it here https://github.com/o-jasper/PegasusJs, i didnt upload because they should have just put a pubkey and a proof-of-work on there or something. Either way.. dont feel like logging into anything.

**Pull request closed without merging**
